version: '3.4'

services:
  dockercrud:
    image: crudonit:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
  
  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=vV5r9tn0M4@
      - ACCEPT_EULA=Y
    ports:
      - "1440:1433"